// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMXGGYWI_3uZ0ECyOXHjX_F4a4QiNRRo0',
    appId: '1:766390593774:web:dc694b00a7ec125179abff',
    messagingSenderId: '766390593774',
    projectId: 'stock-medicale-2024',
    authDomain: 'stock-medicale-2024.firebaseapp.com',
    storageBucket: 'stock-medicale-2024.appspot.com',
    measurementId: 'G-QPQJFH6GS8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbkS6gSi28m3mizdgcn465cnq9c5SeNs0',
    appId: '1:766390593774:android:64ddf0c1a33876ac79abff',
    messagingSenderId: '766390593774',
    projectId: 'stock-medicale-2024',
    storageBucket: 'stock-medicale-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHGqp30S15spWEMhNkwtqSijZOTvCLbvc',
    appId: '1:766390593774:ios:9595756f471bd25079abff',
    messagingSenderId: '766390593774',
    projectId: 'stock-medicale-2024',
    storageBucket: 'stock-medicale-2024.appspot.com',
    iosBundleId: 'com.example.stockMedical',
  );
}
